version: "3"

services:
  broker-mqtt-sales:
    image: eclipse-mosquitto
    ports:
      - "9001:9001"
      - "1883:1883"
    volumes:
      - tpi-broker-mqtt-data-sales:/mosquitto/data            
  store-mongo-sales:
    image: mongo:4
    ports:
      - "27017:27017"
    environment: 
        - storageEngine=wiredTiger
    volumes: 
      - tpi-store-mongo-db-sales:/data/db
  keycloak-mysql-sales:
     image: mysql:5.6
     ports:
       - "3306:3306"
     environment:
         - MYSQL_ROOT_PASSWORD=keycloak
         - MYSQL_DATABASE=keycloak
         - MYSQL_USER=keycloak
         - MYSQL_PASSWORD=keycloak
     volumes:
       - tpi-keycloak-mysql-data-sales:/var/lib/mysql
  keycloak-sales:
       image: nebulaetpi/keycloak:latest
       environment:
         - MYSQL_ADDR=keycloak-mysql-sales
         - MYSQL_PORT_3306_TCP_ADDR=keycloak-mysql-sales
         - MYSQL_PORT_3306_TCP_PORT=3306
         - KEYCLOAK_USER=keycloak
         - KEYCLOAK_PASSWORD=keycloak
         - MYSQL_DATABASE=keycloak
         - MYSQL_USER=keycloak
         - MYSQL_PASSWORD=keycloak
         - SERVICE_PORTS=8080
       ports:
         - 8443:8443
         - 8080:8080
         - 9990:9990
       volumes:
         - tpi-keycloak-data-sales:/opt/jboss/keycloak/standalone/data      
       depends_on: 
         - keycloak-mysql-sales
volumes: 
  tpi-store-mongo-db-sales:
  tpi-broker-mqtt-data-sales:
  tpi-keycloak-mysql-data-sales:
  tpi-keycloak-data-sales: