"Hello world sample, please remove"
type HelloWorldmsnamepascal{
  "text"
  sn: String!  
}

type Query {
  "Hello world sample, please remove"
  getHelloWorldFrommsnamepascal: HelloWorldmsnamepascal
}

type Subscription {
  "Hello world sample, please remove"
  msnamepascalHelloWorldSubscription: HelloWorldmsnamepascal  
}