type CommandResponse {
  "Response code"
  code: Int
  "Response message"
  message: String
}

"Wallet info."
type PosWallet {
  "Wallet ID"
  _id: ID!
  "Owner fullname"
  fullname: String
  "Ownberdocument ID"
  documentId: String
  "ops: CLIENT | BUSINESS | USER | DRIVER"
  type: String
  "pocket info"
  pockets: PosPocket!
  "Wallet state"
  spendingState: String
  "Minimum amount operation"
  minAmountOperation: Int
  "Business ID"
  businessId: String
  "active status"
  active: Boolean
}

type PosPocket{
  "Main pocket"
  main: Float
  "bonus pocket"
  bonus: Float
}

type SalesPosWalletTransaction{
  "Wallet ID"
  _id: ID!
  "Timestamp where the transaction was created"
  timestamp: BigInt!
  "ID of the wallet associated with the transaction"
  walletId: String
  "Transaction type"
  type: String!
  "Transaction concept"
  concept: String!
  "Indicates which was the used pocket"
  pocket: String
  "Amount associated to the transaction"
  amount: Float!
  "User that performs the operation that create the transaction"
  user: String!  
  "Notes"
  notes: String
}
type VehicleSubscriptionPrices {
  month: Int
  week: Int
  day: Int
}

type Query {
  salesWalletsByFilter(filterText: String, businessId: String, limit: Int): [PosWallet]
  SalesPosProductPrices(businessId: String!): VehicleSubscriptionPrices
}

type Mutation {
  SalesPosReloadBalance(walletId: String!, businessId: String!, amount: Int!): CommandResponse
  SalesPosPayVehicleSubscription(walletId: String!, businessId: String!, plate: String!, pack: String!, qty: Int!): CommandResponse
  SalesPosBalanceWithdraw(walletId: String!, businessId: String!, amount: Int!): CommandResponse
}

type Subscription {
  SalesPoswalletsUpdates(walletId: String!): PosWallet  
}