apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos
  template:
    metadata:
      labels:
        app: pos
    spec:      
      containers:
      - image: DOCKERHUB/pos.backend.pos:0.0.39
        name: pos
        volumeMounts:
        - name: google-application-credentials
          mountPath: "/etc/GOOGLE_APPLICATION_CREDENTIALS"
          readOnly: true
        resources:
          requests:
            cpu: "50m"
        env:     
        # EVENT STORE CONFIG 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/GOOGLE_APPLICATION_CREDENTIALS/gcloud-service-key.json  
        - name: EVENT_STORE_BROKER_TYPE
          value: PUBSUB
        - name: EVENT_STORE_BROKER_EVENTS_TOPIC
          value: events
        - name: EVENT_STORE_STORE_TYPE
          value: MONGO
        - name: EVENT_STORE_STORE_URL
          value: mongodb://dbevents-0.dbevents:27017,dbevents-1.dbevents:27017,dbevents-2.dbevents:27017/test?replicaSet=rs0
        - name: EVENT_STORE_STORE_AGGREGATES_DB_NAME
          value: Aggregates
        - name: EVENT_STORE_STORE_EVENTSTORE_DB_NAME
          value: EventStore
        # INTERNAL MONGO DB CONFIG
        - name: MONGODB_URL
          value: mongodb://sale-mongo:27017
        - name: MONGODB_DB_NAME
          value: sales
        # JWT CONGIF        
        - name: JWT_PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              name: keycloak-jwt-public-key
              key: jwt_public_key          
        # API - EMI-GATEWAY CONFIG
        - name: EMI-GATEWAY_REPLIES_TOPIC_SUBSCRIPTION
          value: emi-gateway-replies-topic-mbe-sales
        - name: REPLY_TIMEOUT
          value: '2000'
        - name: BROKER_TYPE
          value: PUBSUB
        # RESET LOCK INITIALIZE BACKED
        - name: LOCKVERSION
          value: "05_04__3"
        # BACKEND PARAMETERS
        - name: GMT_TO_SERVE
          value: "GMT-5"
        - name: VEHICLE_SUBS_PRICES
          value: '{ "day": "2000", "week": "12000", "month": "40000" }'
        
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials
      